

default_platform(:android)

platform :android do
  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :firebase_distribution do
    sh "flutter clean"
    sh " flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
            app: "1:96068686754:android:543c05341b2598c7b158fb",
            testers: "tester1@company.com, tester2@company.com",
            release_notes: "Lots of amazing new features to test out!",
            #to secure var when use fastlane withe github actiones, else lib flutter_dotenv 
            firebase_cli_token: ENF["FIREBASE_CLI_TOKEN"],
            testers: "malakesam2003@gmail.com",
            android_artifact_type: "APK",
            android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
            release_notes: "First Fastlane App Distribution"
          )
  end
end
# in beta deployment in fastlane 
# Firebase App Distribution section
# run fastlane add_plugin firebase_app_distribution
# then from docs firebase cli run firebase login:ci
# then copy the token and paste it in the firebase_cli_token
# then run fastlane android firebase_distribution (this will build the app and upload it to firebase)
