name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3  # Updated to v3
        with:
          java-version: '11'
          distribution: 'temurin'
    
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: '3.13.0'  # Specify a version for stability

      - name: Setup Ruby and install dependencies
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: android
          
      - name: Install Fastlane and dependencies
        working-directory: android
        run: |
          gem install fastlane
          bundle install
          
      - name: Run Fastlane distribution
        working-directory: android
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
          # Add other required secrets here
        run: |
          bundle exec fastlane firebase_distribution